const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('munroe', {
  bootstrap: () => ipcRenderer.invoke('munroe:bootstrap'),
  chooseProject: () => ipcRenderer.invoke('munroe:project:choose'),
  listProjects: () => ipcRenderer.invoke('munroe:projects:list'),
  loadProject: (cwd) => ipcRenderer.invoke('munroe:project:load', cwd),
  projectStatus: (cwd) => ipcRenderer.invoke('munroe:project:status', cwd),
  updateProject: (cwd, updates) => ipcRenderer.invoke('munroe:project:update', cwd, updates),
  openProject: (cwd) => ipcRenderer.invoke('munroe:project:open', cwd),
  listConversations: (cwd) => ipcRenderer.invoke('munroe:conversations:list', cwd),
  newConversation: (cwd) => ipcRenderer.invoke('munroe:conversation:new', cwd),
  appendMessage: (cwd, id, message) => ipcRenderer.invoke('munroe:conversation:append', cwd, id, message),
  deleteConversation: (cwd, id) => ipcRenderer.invoke('munroe:conversation:delete', cwd, id),
  renameConversation: (cwd, id, title) => ipcRenderer.invoke('munroe:conversation:rename', cwd, id, title),
  clearConversations: (cwd) => ipcRenderer.invoke('munroe:conversations:clear', cwd),
  send: (payload) => ipcRenderer.invoke('munroe:chat:send', payload),
  startTurn: (payload) => ipcRenderer.invoke('munroe:turn:start', payload),
  interruptTurn: (turnId) => ipcRenderer.invoke('munroe:turn:interrupt', turnId),
  approveTurn: (payload) => ipcRenderer.invoke('munroe:turn:approve', payload),
  listThreads: (query) => ipcRenderer.invoke('munroe:threads:list', query),
  renameThread: (id, title) => ipcRenderer.invoke('munroe:threads:rename', id, title),
  deleteThread: (id) => ipcRenderer.invoke('munroe:threads:delete', id),
  listCheckpoints: (cwd) => ipcRenderer.invoke('munroe:checkpoints:list', cwd),
  createCheckpoint: (cwd) => ipcRenderer.invoke('munroe:checkpoints:create', cwd),
  rollbackCheckpoint: (cwd, id) => ipcRenderer.invoke('munroe:checkpoints:rollback', cwd, id),
  runSlash: (command, cwd) => ipcRenderer.invoke('munroe:slash', command, cwd),
  cronList: () => ipcRenderer.invoke('munroe:cron:list'),
  cronPause: (id) => ipcRenderer.invoke('munroe:cron:pause', id),
  cronResume: (id) => ipcRenderer.invoke('munroe:cron:resume', id),
  cronRun: (id) => ipcRenderer.invoke('munroe:cron:run', id),
  cronDelete: (id) => ipcRenderer.invoke('munroe:cron:delete', id),
  cronCreate: (payload) => ipcRenderer.invoke('munroe:cron:create', payload),
  workspaceAdd: (cwd, folder) => ipcRenderer.invoke('munroe:workspace:add', cwd, folder),
  workspaceChoose: (cwd) => ipcRenderer.invoke('munroe:workspace:choose', cwd),
  workspaceRemove: (cwd, folder) => ipcRenderer.invoke('munroe:workspace:remove', cwd, folder),
  addAttachment: (payload) => ipcRenderer.invoke('munroe:attachments:add', payload),
  about: () => ipcRenderer.invoke('munroe:about'),
  memoryStatus: () => ipcRenderer.invoke('munroe:systems:memory'),
  memoryRead: (filePath) => ipcRenderer.invoke('munroe:systems:memory:read', filePath),
  listProfiles: () => ipcRenderer.invoke('munroe:systems:profiles'),
  computerUseStatus: () => ipcRenderer.invoke('munroe:systems:computer-use'),
  computerUseDoctor: () => ipcRenderer.invoke('munroe:systems:computer-use:doctor'),
  onTurnEvent: (handler) => {
    const listener = (_event, payload) => handler(payload);
    ipcRenderer.on('munroe:turn:event', listener);
    return () => ipcRenderer.removeListener('munroe:turn:event', listener);
  },
})